config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root                 'static_pages#home'
  get     'help'    => 'static_pages#help', as: 'help'
  get     'about'   => 'static_pages#about', as: 'about'
  get     'contact' => 'static_pages#contact', as: 'contact'
  get     'faq'     => 'static_pages#faq', as: 'faq'

  resources :categories do
    resources :goals
  end


  resources :goals, only: :index

  resources :ingredients
  resources :products

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category    :string
#  category_id :integer
#

class Goal < ActiveRecord::Base
  belongs_to :category
  has_many :products, dependent: :destroy

  def self.most_recent_first
    self.all.order('created_at DESC')
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  # respond_to :js

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
    @category = Category.find(params[:category_id])

  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to category_goal_path(@goal.category_id, @goal), notice: 'Goal was successfully created.'}
        format.json { render :show, status: :created, location: @goal }
        format.js

      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:title, :description, :category_id)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= simple_form_for ([@category, @goal]) do |f| %>
<% if @goal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

    <ul>
    <% @goal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :category%>
  <%= f.button :submit %>
<% end %>

app/views/goals/_goal.html.erb
<%= div_for goal do %>

  <h3><%= goal.name %></h3>

  <ul>
   <li><%= link_to "Edit Task", new_category_goal_path, remote: true %></li>
   <!--
   <li><%= link_to "Mark Complete", complete_path, remote: true %></li>
   <li><%= link_to "Delete Task", task, remote: true, method: :delete %></li>
   -->
  </ul>
<% end %>

app/views/goals/create.js.erb
$('form').hide();
$('.relevant-goals').append('<%= j render partial: "goal", locals: {goal: @goal} %>');
$('.new-goal-button').show();

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Goals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.name %></td>
        <td><%= goal.description %></td>
        <td><%= link_to 'Show', category_goal_path(goal.category_id, goal) %></td>
        <td><%= link_to 'Edit', edit_category_goal_path(goal.category_id, goal) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Goal', new_category_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/new.js.erb
$('.new-goal-button').after('<%= j render('form') %>');
$('.new-goal-button').hide();

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1><%= @goal.name %></h1>
  <p>
    <strong>Description:</strong>
    <%= @goal.description %>
  </p>
</div>
<div class="container">
  <%= link_to 'Edit', edit_category_goal_path(@goal.category_id, @goal) %> |
  <%= link_to 'Back', goals_path %>
</div>
<br>
<br>

<div class="container">
  <h3>Products</h3>
  <p>Some explanation about the products</p>
  <table class="table table-striped">
    <thead>
      <tr>
          <th></th>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Servings</th>
          <th>Size</th>
          <th>Family</th>
          <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @goal.products.each do |product| %>
      <% goal =  Goal.find_by(id: product.goal_id) %>
        <tr>
          <td><div class="thumbnail-image"> <%= image_tag product.image.url(:thumb) %></div></td>
          <td><a href="<%=product_path(product) %>"><%= product.name %></a></td>
          <td><a href="<%=product_path(product) %>"><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.serving_size %></td>
          <td><%= product.product_size %></td>
          <td><%= product.family %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>