config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root                 'static_pages#home'
  get     'help'    => 'static_pages#help', as: 'help'
  get     'about'   => 'static_pages#about', as: 'about'
  get     'contact' => 'static_pages#contact', as: 'contact'
  get     'faq'     => 'static_pages#faq', as: 'faq'

  resources :categories do
    resources :goals
  end


  resources :goals, only: :index

  resources :ingredients
  resources :products

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :goals, dependent: :destroy
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @category = Category.new

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @goals = set_category.goals
  end

  # GET /categories/new
  def new
    @category = Category.new
    # respond_to do |format|
    #   format.json { render json: @category }
    # end
  end

  # GET /categories/1/edit
  def edit

  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit_description.html.erb
<%= simple_form_for category do |f| %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-md-4">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field col-md-4">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions col-md-4">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="container">
    <h2>Categories</h2>
    <p>Some Content to explain stuff</p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Index</th>
          <th>Goal</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></a></td>
            <td><a href="<%=category_path(category) %>"><%= category.name %></a></td>

            <td>
            <div class="category-description" >
              <a href="<%=category_path(category) %>"><%= category.description %></a>
            </div>
            </td>


            <td>
            <div class="edit-category-toggle" style="display:none">
              <%= render 'edit_description', category: category %>
            </div>
            </td>

            <td><button type="button" class="btn btn-success btn-sm edit-category-description" ><%= link_to 'Edit Description', new_category_path %> </button></td>
            <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="container">
    <div class="container new_category_click">
        <button type="button" class="btn btn-success btn-sm btn-custom" ><%= link_to 'New Category', new_category_path %> </button>
    </div>
    <div class="container back_category_click" style="display:none">
        <button type="button" class="btn btn-success btn-sm btn-custom" >Back</button>
    </div>

    <div class="row">
      <div class="new_category_form col-md-8" style="display:none">
        <%= render 'form' %>
      </div>
    </div>

  </div>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="container">
    <h1><%= @category.name %></h1>
    <p>
      <strong>Description:</strong>
      <%= @category.description %>
    </p>
  </div>

  <div class="container">
    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Back', categories_path %>
  </div>
</div>

  <br>

<div class="container">
  <div class="container relevant-goals">
    <h3>Relevant Goals</h3>
    <p>Some specific goals relevant to your high level goal</p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Index</th>
          <th>Goal</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <ol>
          <% counter = 1 %>
          <% @goals.each do |goal| %>
            <tr>
              <td><%= counter %></td>
              <td><a href="<%= category_goal_path(@category, goal )%>"><%= goal.name =%></a></td>
              <td><a href="<%= category_goal_path(@category, goal )%>"><%= goal.description %></a></td>
            </tr>
          <% counter += 1 %>
          <% end %>
        </ol>
      </tbody>
    </table>
    |<%= link_to 'New Goal', new_category_goal_path(@category), remote: true, class: "new-goal-button"%>|
  </div>
</div>